### ISSUE TITLE
"Could not load XPCOM"

### ISSUE THREAD

**Issue by skynurd** [echelon-theme/echelon#18]
I get the error in the title when i replace the xul.dll file in the program files directory where firefox 115.7.0 esr is located. Any workaround? or explain to me what i'm missing/doing wrong here.

**Comment by ephemeralViolette** [comment]
Wrong repo. Try 115.6 or build it yourself.

**Comment by skynurd** [comment]
yeah, just downgraded to 115.6. works now. thanks.
