### ISSUE TITLE
Will "echelon" be available in the latest versions of Firefox and not just in 115ESR?

### ISSUE THREAD

**Issue by TeleTimofeya** [echelon-theme/echelon#19]
Will "echelon" be available in the latest versions of Firefox and not just in 115ESR?

**Comment by ImSwordQueen** [comment]
Mozilla removed a lot of native stuff from Firefox since 117 that would make it slightly harder to port the theme past 116, also, with each new version there's a risk that the theme might break or stuff that echelon uses get removed out of nowhere.

**Comment by aubymori** [comment]
> Will "echelon" be available in the latest versions of Firefox and not just in 115ESR?

Echelon will be available for 128esr (next ESR) once it comes out and the [native controls patch](https://github.com/ephemeralViolette/firefox-native-controls). I should mention that Echelon actually works pretty well on latest minus the absence of certain native controls which is exactly why we're still on 115.
