### ISSUE TITLE
this dot

### ISSUE THREAD

**Issue by inf0renv** [echelon-theme/echelon#25]
is a smol error, but once you look at it, you will never forget its there
FILL THE FOKIN DOT PLEASE I CANT SLEEP
![fuckin dot](https://github.com/echelon-theme/echelon/assets/159966622/029ab375-aff7-47fa-8899-30ebef72a7ba)

**Comment by travy-patty** [comment]
Set the mask 1px shorter in width and height.

**Comment by inf0renv** [comment]
thank you so much now i can sleep
