### ISSUE TITLE
Finish button in the first time setup not working

### ISSUE THREAD

**Issue by FanACYT** [echelon-theme/echelon#29]

**Comment by trev3d** [comment]
Are you on Firefox 115 ESR? This happened to me when I incorrectly tried installing this on the latest version of Firefox

**Comment by megakarlach** [comment]
Same thing except on Waterfox G6.0.9, which is Firefox 115 ESR fork.

**Comment by Erizur** [comment]
Pretty sure this has been fixed a long time ago.

**Comment by FanACYT** [comment]
yeah the newer versions fixed that issue
