### ISSUE TITLE
Titlebar hidden behind address bar in popups unless menubar is enabled

### ISSUE THREAD

**Issue by lukgth** [echelon-theme/echelon#32]
What the title says, issue is present on all styles.

Running Firefox ESR 115.7 and newest build of Echelon.

Before enabling the menubar:
![NVIDIA_Share_p17rSiJ7TI](https://github.com/echelon-theme/echelon/assets/63365889/40bd77de-72d9-4ad7-bcf1-06d1de64182c)

After enabling the menubar:
![NVIDIA_Share_LOkhJTN2qg](https://github.com/echelon-theme/echelon/assets/63365889/cf31c8e3-14da-4a9b-8d20-cc27763b44f8)

**Comment by travy-patty** [comment]
Fix in 15140796f1556abd0158668d7ccb9c42d366badf by reverting to a older script version, a better method needs to be done for it.
