### ISSUE TITLE
Echelon not working

### ISSUE THREAD

**Issue by UnrealLuke** [echelon-theme/echelon#35]
So I've installed Firefox ESR 115.7. Followed the instructions, put the Profile Folder contents into the Profile Folder and the Firefox Folder contents into the Firefox Directory. I restarted my Computer and it still doesn't work

**Comment by nabriouso** [comment]
If you want help. Please be more specific.

**Comment by UnrealLuke** [comment]
Okay, I'll explain it specific. (Might not be good wording as I am not English)

So I was interested in making my Computer look like Windows 7 as I am a big fan of it. I went in contact with a friend and he showed me the tools to make it look like it's Windows 7. Then I saw a browser have a matching look for what I was searching, so I asked him what browser. He told me it was Firefox and I installed it, he also told me I need to install Echelon. He sent me the link for the instruction and I downloaded the xul.dll and the Public Release 1.0. I replaced the xul.dll and restarted Firefox ESR 115.7. Then I wrote into the search bar "about:support", I opened the Profile Folder and my Firefox Directory. I put the contents of the Firefox Folder into the Firefox Directory and the Profile Folder contents into the Firefox Profile Folder. I restarted my Firefox, yet it still didn't show the Echelon Options, so I restarted my Computer (Windows 10 Pro 22H2). I opened Firefox and still didn't have the Echelon Options, and I really want the classic feeling.

**Comment by YukisCoffee** [comment]
Did you put the profile files into the right folder?

**Comment by UnrealLuke** [comment]
Yes, here's a photo of my Profile Folder.
![image_2024-02-17_235238594](https://github.com/echelon-theme/echelon/assets/160363249/71e6662e-b9fd-4b8d-9987-1bf75eec3009)

**Comment by YukisCoffee** [comment]
That's not your profile folder.

**Comment by UnrealLuke** [comment]
Well, that's weird. Let me send a video recording

**Comment by UnrealLuke** [comment]
I'm so stupid, I didn't read the thing on the left. I just clicked random stuff

**Comment by UnrealLuke** [comment]
Now it works.. I guess I was stupid enough to not read

**Comment by UnrealLuke** [comment]
Blame me for being stupid, but thanks for helping me out I guess.

**Comment by nabriouso** [comment]
> Blame me for being stupid, but thanks for helping me out I guess.

It’s not a big deal, let this be a lesson for the future, read the README’s!
