### ISSUE TITLE
Couldn't load XPCOM

### ISSUE THREAD

**Issue by Nasarwo** [echelon-theme/echelon#39]
it error start appears when i replace xul.dll
![image](https://github.com/echelon-theme/echelon/assets/111646639/416d9937-7d66-4c5a-abfc-49f0a7f5c35e)

**Comment by aubymori** [comment]
> it error start appears when i replace xul.dll ![image](https://private-user-images.githubusercontent.com/111646639/307296223-416d9937-7d66-4c5a-abfc-49f0a7f5c35e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTc5NTEsIm5iZiI6MTcwODY5NzY1MSwicGF0aCI6Ii8xMTE2NDY2MzkvMzA3Mjk2MjIzLTQxNmQ5OTM3LTdkNjYtNGM1YS1hYmZjLTQ5ZjBhN2Y1YzM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxNDE0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2U0MTliYTcyZmI4Yzk5ODM1ZTA1M2M3YzU5MTg5YjAyOGUzNWYwMjk4YTJmZDI4YTEyNTJkOWQwMzY4YTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lhHwNdatUtIZSmoTgHNwG3RenpysXt2yc7gyIzWSRGU)

Not an Echelon issue.
