### ISSUE TITLE
Scrollable bookmarks not showing in bookmarks menu or toolbar..

### ISSUE THREAD

**Issue by Wiiplay123** [echelon-theme/echelon#40]
Looks like the bookmarks only disappear when scrolling is required. This issue affects both the bookmarks menu and the bookmarks toolbar.

I've included pictures of a working and non-working bookmarks toolbar folder.

![2024-02-25 15_26_03-](https://github.com/echelon-theme/echelon/assets/9746793/f1bf3913-81ae-4f12-a064-88dd39da14ed)
![2024-02-25 15_24_54-](https://github.com/echelon-theme/echelon/assets/9746793/16fd9ffc-5aca-4d3b-a43d-97c3283044b9)

**Comment by travy-patty** [comment]
Fixed in 7a5fea597ad46cfb7101865e8e1a6445b5101dd9
