### ISSUE TITLE
I don't know how to update

### ISSUE THREAD

**Issue by SoftwareType** [echelon-theme/echelon#45]
Random, but I just found out there's an update thing for Echelon, but it seems like there's just 1 change and idk how to get it updated
![image](https://github.com/echelon-theme/echelon/assets/158858932/cc3b6bf4-4c48-440f-9b19-de62ca22367d)
It doesn't seem to be having any tutorial for it aswell

**Comment by angelbruni** [comment]
Replace the old chrome folder files with the new ones in the repo (or wait for a new build release).

**Comment by aubymori** [comment]
use discussions
