### ISSUE TITLE
Downloaded latest release but echelon still complains about there being a new update

### ISSUE THREAD

**Issue by Pepeshki** [echelon-theme/echelon#50]
![image](https://github.com/echelon-theme/echelon/assets/75133653/5403f40e-09bd-46f9-b2a8-cce94c671ba5)
Is there any way to fix this without disabling the new update notification?

**Comment by Kiki79250CoC** [comment]
in that case, open the build.txt file in the chrome folder and modify the value in it (put something like "400") and it should stop complaining

I say "400" but you can technically put what you want in it.
