### ISSUE TITLE
Bookmark backgrounds appearing fully transparent

### ISSUE THREAD

**Issue by DaniJam005** [echelon-theme/echelon#56]
When I click on my bookmark bar folders, all of my bookmarks' backgrounds are completely transparent
![image](https://github.com/echelon-theme/echelon/assets/118861261/7fe4e255-752a-4534-a3b8-92243eb87c06)
Firefox Version : Version 123.0 (64-bit)

**Comment by aubymori** [comment]
> Firefox Version : Version 123.0 (64-bit)

Not supported. You must use 115 ESR. This happens due to the lack of native menu appearance properties.
