### ISSUE TITLE
Can you please add the "Strata v29+" theme here, like in the "Classic Theme Restorer" plugin that was used in Firefox 29-56?

### ISSUE THREAD

**Issue by TeleTimofeya** [echelon-theme/echelon#58]
![1709549317905](https://github.com/echelon-theme/echelon/assets/149526974/6c183880-f185-4a79-89b0-dfa710b0dbed)
![1709544756314](https://github.com/echelon-theme/echelon/assets/149526974/84492952-8bae-4175-92a3-d436297e23b7)

**Comment by aubymori** [comment]
Echelon is meant to restore Strata as it was when it was in the Firefox browser, not as it was when you used third-party add-ons to restore it in versions of Firefox that had Australis.
