### ISSUE TITLE
Window buttons are blacked out on Windows 11

### ISSUE THREAD

**Issue by commandcontrolQ** [echelon-theme/echelon#6]
Firefox 115.7esr running on Windows 11 Enterprise 23H1

Window buttons appear blacked out regardless of theme selection.
![image](https://github.com/echelon-theme/echelon/assets/124590064/86b38ac3-9ce8-4721-a43a-89e4117cb915)

**Comment by commandcontrolQ** [comment]
A fix was found - this can be fixed by disabling DWM composition (not recommended, causes titlebar to revert to Windows 7 with larger window buttons) or by changing the 'Override Windows Version' in 'Native Controls' to Windows 10 (recommended).

**Comment by aubymori** [comment]
> Firefox 115.7esr running on Windows 11 Enterprise 23H1
> 
> Window buttons appear blacked out regardless of theme selection. ![image](https://private-user-images.githubusercontent.com/124590064/302299028-86b38ac3-9ce8-4721-a43a-89e4117cb915.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDI1NTksIm5iZiI6MTcwNzE0MjI1OSwicGF0aCI6Ii8xMjQ1OTAwNjQvMzAyMjk5MDI4LTg2YjM4YWMzLTljZTgtNDcyMS1hNDNhLTg5ZTQxMTdjYjkxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxNDEwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzllZWY3MTNmYzhiZThkYzJjNWQ1NGU2NzZjNDY5MDUzNDRkZWI2MzMyMjhkOGI2MjhmZTM1YmQ0ZDVjNjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UhGQwx5pwXmAEVe93AiSM5lQPwxFuuJ2TAnP23err2w)

Please set the preference `gfx.webrender.software` to `true` in `about:config`. This will make Firefox use the DirectX backend which fixes this.

**Comment by TorutheRedFox** [comment]
that's kinda a poor workaround as it causes the browser to be a bit laggy and use a ton of CPU

**Comment by aubymori** [comment]
> that's kinda a poor workaround as it causes the browser to be a bit laggy and use a ton of CPU

Misleading pref name, it actually uses DirectX.

**Comment by trev3d** [comment]
> Exact opposite.

My personal website (trev3d.com) chugs with `gfx.webrender.software`. I'm not sure this is true.

**Comment by Xdmg01** [comment]
> > Exact opposite.
> 
> My personal website [(trev3d.com)](http://trev3d.com) with several videos chugs with `gfx.webrender.software`. I'm not sure this is true. I'm going to poke around the web with some profiling tools.

This is not true, software WebRender doesn't use DirectX for it's backend, it only uses it for the compositor and leads to worse performance, especially when rendering high resolution videos

A better solution would be disabling the compositor setting the pref `gfx.webrender.compositor` to false and disabling `gfx.webrender.software`

**Comment by ephemeralViolette** [comment]
> > > Exact opposite.
> > 
> > 
> > My personal website [(trev3d.com)](http://trev3d.com) with several videos chugs with `gfx.webrender.software`. I'm not sure this is true. I'm going to poke around the web with some profiling tools.
> 
> This is not true, software WebRender doesn't use DirectX for it's backend, it only uses it for the compositor and leads to worse performance, especially when rendering high resolution videos
> 
> A better solution would be disabling the compositor setting the pref `gfx.webrender.compositor` to false and disabling `gfx.webrender.software`

Mask doesn't render at all for me with this configuration.

![image](https://github.com/echelon-theme/echelon/assets/28045018/72a7ba18-0b4b-4d55-bfab-f8b977bd01b9)

**Comment by Xdmg01** [comment]
It looks like the caption button mask only renders when the main-window background isn't transparent using hardware WebRender, so it works with custom themes but not with the fog shadow
Still, software WebRender performance is really bad with video playback and this can be seen using the profiler pref `gfx.webrender.debug.profiler`

Software WebRender, playing a video at 1080p 60fps on a second window while scrolling:
![profilersw](https://github.com/echelon-theme/echelon/assets/24902344/1c5dad90-2945-414a-b13c-edc208acada9)

Hardware WebRender, same scenario:
![profilerhw](https://github.com/echelon-theme/echelon/assets/24902344/a74affbb-d79f-4eba-b5c4-10da5bc77196)
