### ISSUE TITLE
Aero not working

### ISSUE THREAD

**Issue by lucassilvas1** [echelon-theme/echelon#62]
I installed Echelon, and I was under the impression that you could get Aero if you use DWMBlurGlass with it, but it's not working (to be clear, DWMBlurGlass does work on other windows).

This is what it looks like for me:
![image](https://github.com/echelon-theme/echelon/assets/52336985/70b95033-069a-454d-a4ae-d63945a4e1f0)

Here's what some other windows look like with DWMBlurGlass and the Aero10 theme:
![image](https://github.com/echelon-theme/echelon/assets/52336985/597a939f-35fe-49d2-97ee-3bb434bf76d3)

As you can see in the image, the title bar is completely opaque, and the control buttons look completely out of place. Using light mode on Windows does "fix" the control buttons, but the title bar remains opaque.

I'm not sure if this is an Echelon or a DWMBlurGlass problem, or if Echelon even supports Aero, so apologies in advance.

OS: Windows 10 22H2
Firefox: 115.8.0ESR x64
Echelon: Current build
xui.dll patch installed

**Comment by ImSwordQueen** [comment]
Enable force glass in the echelon settings
![image](https://github.com/echelon-theme/echelon/assets/52015098/1236bd8f-6325-4248-a463-d0fa20a98c20)

**Comment by lucassilvas1** [comment]
> Enable "Override Glass" in the echelon settings ![image](https://private-user-images.githubusercontent.com/52015098/312992433-1236bd8f-6325-4248-a463-d0fa20a98c20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDk5NTQsIm5iZiI6MTcxMDQ0OTY1NCwicGF0aCI6Ii81MjAxNTA5OC8zMTI5OTI0MzMtMTIzNmJkOGYtNjMyNS00MjQ4LWE0NjMtZDBmYTIwYTk4YzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDIwNTQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYjI2NGRjODliOTA1YTMxMTkwZjViNjhkMjk1OTFmMTUwMWIyMDZmZGZjZjI0OThkODgyZDlhYjlmMjU4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CSlZm-qTANxrxJVnTHK2d37lQCo9V3jSH09knaeQK94)

Thank you for replying so quickly. I did that and Aero is still not working, it did fix the controls for the most part, although it's still not quite right.

![image](https://github.com/echelon-theme/echelon/assets/52336985/024acb07-6114-4d85-be60-a6142b92191b)

Any idea?

Thanks.

**Comment by ImSwordQueen** [comment]
Modify these settings until the buttons work
![image](https://github.com/echelon-theme/echelon/assets/52015098/3ecbe153-222b-42e7-a16f-fc1e391150f1)

**Comment by lucassilvas1** [comment]
> Modify these settings until the buttons work ![image](https://private-user-images.githubusercontent.com/52015098/312996344-3ecbe153-222b-42e7-a16f-fc1e391150f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NTA4OTgsIm5iZiI6MTcxMDQ1MDU5OCwicGF0aCI6Ii81MjAxNTA5OC8zMTI5OTYzNDQtM2VjYmUxNTMtMjIyYi00MmU3LWExNmYtZmMxZTM5MTE1MGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDIxMDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YTBhN2Y4YjY2ZGM3N2EyZDk2OTViNzRmOTk0ZWUwMDI0ZTY1ZGY0Yzg3OTUyYzc1ZjNhN2EzNTI2MDI0ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hcNFxVBe4WP8nAIrA2oQh1xOLkH9K1hNXiTPEsA1w24)

These seem to fix the buttons
![image](https://github.com/echelon-theme/echelon/assets/52336985/3865a783-38df-4ac4-9fec-53b5f8be4310)

Any idea how to get Aero to work, on any browser really, no need to be Firefox.

**Comment by ImSwordQueen** [comment]
The only browsers that support aero are firefox pre 116 and supermium. all browsers removed aero support (this is due to chromium removing it after 8.1's EoL)

**Comment by lucassilvas1** [comment]
> The only browsers that support aero are firefox pre 116 and supermium. all browsers removed aero support (this is due to chromium removing it after 8.1's EoL)

Shouldn't it work with Echelon, then? I'm on 115.8.0 ESR with DWMBlurGlass installed.

**Comment by ephemeralViolette** [comment]
I believe your theme has a solid background behind there.

**Comment by lucassilvas1** [comment]
> I believe your theme has a solid background behind there.

You mean like a Firefox theme, I haven't installed any, it's a fresh install with Echelon and it looks like this.

**Comment by lucassilvas1** [comment]
> > I believe your theme has a solid background behind there.
> 
> You mean like a Firefox theme, I haven't installed any, it's a fresh install with Echelon and it looks like this.

You could be right, I tried Silverfox and had the same problem, but I changed the theme from Default to Dark just now, and now Aero works. So that's probably the case for Echelon too. Thanks for the help.

**Comment by aubymori** [comment]
@lucassilvas1 Disable dark mode for apps (this configuration).
![image](https://github.com/echelon-theme/echelon/assets/44238627/a4841635-1fbb-47e7-87b6-9652b5f2e7d8)

**Comment by lucassilvas1** [comment]
> @lucassilvas1 Disable dark mode for apps (this configuration). ![image](https://private-user-images.githubusercontent.com/44238627/316595752-a4841635-1fbb-47e7-87b6-9652b5f2e7d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzODk2ODcsIm5iZiI6MTcxMTM4OTM4NywicGF0aCI6Ii80NDIzODYyNy8zMTY1OTU3NTItYTQ4NDE2MzUtMWZiYi00N2U3LTg3YjYtOTY1MmI1ZjJlN2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE3NTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NWFjZGE0YzU4NDdjNzkyMWZhOGEyM2YxMDY1ODIxOGM0YzBjNjYwNWMyMWFmMTM4ZTY3Y2YyNTllNjJhYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xCHVI6NHthM7AmR9VepLl4jzOADySq7IU1xYNQDTyqw)

Just setting the theme to Dark on Echelon fixed it. I can't handle light mode. Now the only issue is that some parts of the UI have black text on dark gray background, but I can live with that.

![image](https://github.com/echelon-theme/echelon/assets/52336985/5512e5b7-d20e-4c81-84f4-57c77dbdc106)

**Comment by KyriiiX** [comment]
> > @lucassilvas1 Disable dark mode for apps (this configuration). ![image](https://private-user-images.githubusercontent.com/44238627/316595752-a4841635-1fbb-47e7-87b6-9652b5f2e7d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzODk2ODcsIm5iZiI6MTcxMTM4OTM4NywicGF0aCI6Ii80NDIzODYyNy8zMTY1OTU3NTItYTQ4NDE2MzUtMWZiYi00N2U3LTg3YjYtOTY1MmI1ZjJlN2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE3NTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NWFjZGE0YzU4NDdjNzkyMWZhOGEyM2YxMDY1ODIxOGM0YzBjNjYwNWMyMWFmMTM4ZTY3Y2YyNTllNjJhYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xCHVI6NHthM7AmR9VepLl4jzOADySq7IU1xYNQDTyqw)
> 
> Just setting the theme to Dark on Echelon fixed it. I can't handle light mode. Now the only issue is that some parts of the UI have black text on dark gray background, but I can live with that.
> 
> ![image](https://private-user-images.githubusercontent.com/52336985/316604715-5512e5b7-d20e-4c81-84f4-57c77dbdc106.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTA5NjQsIm5iZiI6MTcxMjUxMDY2NCwicGF0aCI6Ii81MjMzNjk4NS8zMTY2MDQ3MTUtNTUxMmU1YjctZDIwZS00YzgxLTg0ZjQtNTdjNzdkYmRjMTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE3MjQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYWE2YWFjN2M5MDZmZTRkN2MwYWJiNTViNDMxMjY1NDE1MmUwZGE1YTBlNzM2NGU0OTJjMjVlMjliODNmZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DzG0qoB0gOQwMKuC77FkSw6cDjyqlpMY7_7fVysz93A)

Yeah with Dark mode the UI inputs and tables have this issue, and also some text is white on a mostly white background.

![image](https://github.com/echelon-theme/echelon/assets/67878021/11b8c9ec-e58a-426b-9286-a1640291d99d)
![image](https://github.com/echelon-theme/echelon/assets/67878021/9138a7e2-d4f9-4d04-9595-c6c1369e2135)
![image](https://github.com/echelon-theme/echelon/assets/67878021/08f2b0ad-4bb0-4067-ae5f-1675df980df8)

**Comment by lucassilvas1** [comment]
@KyriiiX I actually stopped using Echelon because of this and due to some serious performance issues on some pages, e.g. the [GitHub homepage](https://github.com/) (when you're not signed in) has some terrible stuttering when scrolling.

**Comment by KyriiiX** [comment]
> @KyriiiX I actually stopped using Echelon because of this and due to some serious performance issues on some pages, e.g. the [GitHub homepage](https://github.com/) (when you're not signed in) has some terrible stuttering when scrolling.

I did "fix" the aforementioned issue by setting the Website appearance to Light, although it obviously breaks Dark mode behavior on other websites. I also do encounter some stuttering/laggyness but I don't believe it to be related to Echelon but to Firefox (as a mainly Chrome-based browser user, they feel a tad more responsive).

**Comment by lucassilvas1** [comment]
> > @KyriiiX I actually stopped using Echelon because of this and due to some serious performance issues on some pages, e.g. the [GitHub homepage](https://github.com/) (when you're not signed in) has some terrible stuttering when scrolling.
> 
> I did "fix" the aforementioned issue by setting the Website appearance to Light, although it obviously breaks Dark mode behavior on other websites. I also do encounter some stuttering/laggyness but I don't believe it to be related to Echelon but to Firefox (as a mainly Chrome-based browser user, they feel a tad more responsive).

I can confirm the stuttering is caused by Echelon, vanilla Firefox has absolutely no stuttering.

**Comment by Erizur** [comment]
Closing as the conversation has gone off-topic.
