### ISSUE TITLE
Weird button window behavior on MacOS

### ISSUE THREAD

**Issue by pulsed3x** [echelon-theme/echelon#63]
Now, I know that macOS isn't really supported but I still wanted to reported my findings. The way the windows work on macOS Mojave on Firefox 115.8.0 ESR. They act normal at first but when you click a second time, it moves on top of the button and makes almost all the options in the menu unclickable. Here's a video to show the issues

https://github.com/echelon-theme/echelon/assets/74111213/77bae380-a35a-47fc-995e-073132068bdd

**Comment by ephemeralViolette** [comment]
We don't have OS X developers (and my GPU is incompatible with any version < 10.12.6), so we can't investigate this. Do you mind looking into it yourself? My assumption is that the issue has to do with the code to restore arrow tip to these popup menus in `echelon_popups.uc.js`.

**Comment by ephemeralViolette** [comment]
Oh wait, I just noticed the Siri icon. Sorry, I thought this was actually Mavericks.

**Comment by pulsed3x** [comment]
> We don't have OS X developers (and my GPU is incompatible with any version < 10.12.6), so we can't investigate this. Do you mind looking into it yourself? My assumption is that the issue has to do with the code to restore arrow tip to these popup menus in `echelon_popups.uc.js`.

That's fine, I can look into that.

**Comment by Erizur** [comment]
My pull request (#66) fixed some macOS issues including this. This is now fixed as it got merged into the main repo. Waiting for the issue to get closed.
