### ISSUE TITLE
aero broken

### ISSUE THREAD

**Issue by indigofairyx** [echelon-theme/echelon#64]
its work the very first time i installed until i restarted firefox and it went black & flat.

tried uninstalling firefox, started from scratch, cant get it to display aero again.

**Comment by Erizur** [comment]
Could you specify if you're using Firefox 115 ESR?
You need to have the native controls patch installed, and you can configure them through the echelon options menu.

**Comment by Erizur** [comment]
Closing as there's little to no information about this issue.

**Comment by indigofairyx** [comment]
sorry,
i initially tried this on the current version of firefox and it worked until i rebooted.
then tried v115.8.0esr, no luck getting it back
then, i gave up on it and uninstalled\started over with firefox.

however thanks for your efforts!!! it was stumbling upon this plugin that lead me to discover[ DWMBlurGlass](https://github.com/Maplespe/DWMBlurGlass) which has brought back aero theming system wide excluding web browsers and uwp, fair trade!
