### ISSUE TITLE
New windows lose the gradient under the tabs, and the refresh button is no longer in the address bar.

### ISSUE THREAD

**Issue by Wiiplay123** [echelon-theme/echelon#68]
When I make a new window, the gradient under the tabs on that window never appears.

Original window on the left, new window on the right.

![2024-03-25 13_28_58-Mozilla Firefox Start Page — Mozilla Firefox](https://github.com/echelon-theme/echelon/assets/9746793/10d12692-ca04-4863-a659-f53ab63a8b8b)

EDIT: After I posted this issue I noticed the refresh button is wrong, too.

**Comment by aubymori** [comment]
tools > userscripts > clear startup cache & restart firefox
absolutely no clue why new windows do this

**Comment by Wiiplay123** [comment]
Thanks, that fixed it!
