### ISSUE TITLE
native controls patch repo deleted

### ISSUE THREAD

**Issue by PF94** [echelon-theme/echelon#69]
https://github.com/ephemeralViolette/firefox-native-controls/ now yields a 404 error

**Comment by commandcontrolQ** [comment]
I can confirm as well, the repo no longer exists. The files however could likely be accessed via the Internet Archive, if the page has been archived, that is.

**Comment by commandcontrolQ** [comment]
I have checked, and there only exist 4 captures for the following URL: https://github.com/ephemeralViolette/firefox-native-controls/releases

**Comment by PF94** [comment]
the better thing would be if someone has git cloned that repository.

**Comment by ImSwordQueen** [comment]
an archived version of the repository + the compiled binaries can be found here: https://github.com/ImSwordQueen/firefox-native-controls

**Comment by PF94** [comment]
don't think it's solved if there's effectively no more way of using an updated firefox esr version with the native controls
