### ISSUE TITLE
issue? does not work with waterfox

### ISSUE THREAD

**Issue by Uneuclid** [echelon-theme/echelon#7]
im not sure if this theme is meant to have waterfox support but it currently does not seem to work for me as i cannot finish the theme install (finish button wont work). is there a better version of waterfox to use, is there a fix, what can i do. also how do i uninstall the theme 

edit: it KINDA works, but the theme doesnt seem to look 100% as it should and i get an install prompt every time i open the browser

**Comment by aubymori** [comment]
not a waterfox issue
also fixed by 26a95f52363e0eca7bf1161307f7de32fb4e0045
