### ISSUE TITLE
cant find new build???

### ISSUE THREAD

**Issue by fishcelery4894** [echelon-theme/echelon#87]
so im on build 338, and when i open firefox, it says "new build 413" something like that, but i cant find it!

also the homepage is broken??? i had silverfox beta before and its trying to find silverfox's homepage instead of echelon.
![this](https://github.com/echelon-theme/echelon/assets/159673412/03f0a86d-1ef2-40a5-9cfc-c02e252f1ee6)
(i have a macos x theme btw)

help me please

**Comment by Erizur** [comment]
about the homepage, it is most likely a config.js issue. you will have to look in about:config, and look in the value of browser.newtab.url. you can have a look at this post for more info: https://support.mozilla.org/en-US/questions/1063118

about the new build, echelon checks updates from the repo itself. you will have to push the new changes from the repo or redownload the repository if you don't use git.
