### ISSUE TITLE
When using DWMBlurGlass on Windows 10 and Mistralis Fog, one of the titlebar parts isn't properly fogged

### ISSUE THREAD

**Issue by ValeraDX** [echelon-theme/echelon#90]
![image](https://github.com/echelon-theme/echelon/assets/108476413/9238c7dc-7537-41bc-87b2-6359646861e2)
Below are attached both the DWMBlurGlass Settings and Echelon Settings (The style is set to Windows 7, it shows as "Windows XP" due to issue #3)
![image](https://github.com/echelon-theme/echelon/assets/108476413/2379c50e-6b69-4616-9164-93224141ad47)
![image](https://github.com/echelon-theme/echelon/assets/108476413/6bac47da-af5e-414d-8e8d-8faed39697b8)
![image](https://github.com/echelon-theme/echelon/assets/108476413/a837ae39-1977-4452-afb6-0e4bdb4429a8)

**Comment by CatmanFan** [comment]
This problem could be mitigated by setting the 'Aero caption button mask' width (e.g. 102 or a similar number for Windows 7 button sizes), which controls the extent of the fogging

**Comment by Erizur** [comment]
This isn't really an issue. Configure the Aero caption button mask setting in the Native Controls tab, inside Echelon Options.
