### ISSUE TITLE
Configuration Error, then opens normally un-themed

### ISSUE THREAD

**Issue by Syreyup** [echelon-theme/echelon#94]
![image](https://github.com/echelon-theme/echelon/assets/89299730/7f3db9b5-7537-49d3-9758-c475dc228828)
Just what the title says, im not sure what I could have done wrong, lmk if you need any details.

Windows 7 Ultimate x64
Firefox Version 115.12.0esr (64-bit)

**Comment by fishcelery4894** [comment]
im also on what you're on but i havent seen this
best of luck i guess, but i did solve one of my own issues by redo-ing the whole process because i previously had silverfox.

**Comment by Erizur** [comment]
This isn't entirely related to Echelon. As a suggestion, you can do a clean installation of Firefox just in case.
